### PR TITLE
Adds feature for /api/chat access via OllamaAPI

### LINKED ISSUE #20: Support roles like for example user, system, assistant
When sending messages directly to the Mistral API (similar to OpenAI API), then one can send messages with different roles, whereas see

- https://platform.openai.com/docs/guides/text-generation/chat-completions-api
- https://cookbook.openai.com/examples/azure/chat_with_your_own_data#code

Is this possible somehow with ollama4j respectively Ollama itself?

### PR DESCRIPTION
**Pull request by AgentSchmecker**
Fixes #20 as the required functionality is provided by the api/chat endpoint on the Ollama API Server. 

The feature adds two endpoints to the OllamaAPI class:

``` java 
  public OllamaResult chat(String model, List<OllamaChatMessage> messages)  throws OllamaBaseException, IOException, InterruptedException, URISyntaxException;

  public OllamaResult chat(OllamaChatRequestModel request);
```

For convienience, a request Builder will be provided, such that the following would create a Request that contains a system prompt as well as a user question:

``` java
OllamaChatRequestModel requestModel = builder.withMessage(OllamaChatMessageRole.SYSTEM,"Some System-Prompt")
           .withMessage(OllamaChatMessageRole.USER,"The User Question").build()
```

The Request model also contains the usual Parameters like Options, template, stream and so on.

### CODE REVIEW

**Comment by AgentSchmecker** [comment]
Implementation for the synchronous part is finished. Here is a short example:

```java
String host = "http://localhost:11434/";
OllamaAPI ollamaAPI = new OllamaAPI(host);
OllamaChatRequestBuilder builder = OllamaChatRequestBuilder.getInstance(OllamaModelType.LLAMA2);
      OllamaChatRequestModel requestModel = builder.withMessage(OllamaChatMessageRole.SYSTEM, "You are a silent bot that only says 'NI'. Do not say anything else under any circumstances!")
             .withMessage(OllamaChatMessageRole.USER,"We need a montage!")
             .build();

      OllamaChatResult chatResult = ollamaAPI.chat(requestModel);
      assertNotNull(chatResult);
      assertFalse(chatResult.getResponse().isBlank());
      assertTrue(chatResult.getResponse().startsWith("NI"));
```

Tests for this case are succesful, next I'll start to write documentation for it, if the Implementation seems okay for you @amithkoujalgi

**Comment by AgentSchmecker** [comment]
Documentation is ready for two use cases, both replying to #20.

@amithkoujalgi would you kindly do a review of this PR? There are some open ends like:

* Async Chat
* Image usage in Messages

Both of them don't seem to be too much trouble, but I think it would make sense to refactor some of the Image Usage / Async logic to be reused by multiple API endpoints, which would delay the initial implementation too much I'd say. What do you think of this?

Cheers!

**Comment by amithkoujalgi** [comment]
Thanks for the PR @AgentSchmecker! Looks good.

**Comment by AgentSchmecker** [comment]
@amithkoujalgi I've seen that the build is broken after the merge. I'll provide a PR to fix this. Sorry for the inconvenience!

**Comment by AgentSchmecker** [comment]
Ok, as I see you have been faster than me, thanks a lot @amithkoujalgi

**Comment by amithkoujalgi** [comment]
Thanks for considering to provide a PR to fix the build @AgentSchmecker. I briefly looked at the javadoc and updated them. 😅 They were minor fixes anyway, so no worries.

Thanks again! Cheers!

**Pull request merged**
