### PR TITLE
Issue #2: Certain requests fail with a 400 Bad Request

### PR DESCRIPTION
**Pull request by reckart**
- writeBytes(String) does not work properly with Unicode characters and may produce invalid UTF-8 - replacing it with an alternative call that converts the JSON string to a proper UTF-8 byte array representation and sends that

### CODE REVIEW

**Comment by reckart** [comment]
Looks like there is an import missing in a file in this PR. I had just pushed an updated, but you already had merged.

How about setting up a GitHub action to build PRs?

**Comment by amithkoujalgi** [comment]
Yeah I saw that an import was missing, and I updated it immediately.
About setting up a GitHub action to build PRs, could you point me to some documentation/example? TBH, GitHub actions is pretty new to me since I started using it only recently. 😆 Any sort of help/directions would be really helpful!

**Comment by reckart** [comment]
Your current GH action builds the main branch and then publishes the SNAPSHOT to Maven Central. 

You may want to set up a second GH action that does not run on `push` but only on `pull_request` and which does not have the step that publishes to Maven Central (i.e. without `Set up Apache Maven Central (Overwrite settings.xml)` and `Publish to GitHub Packages Apache Maven`).

While we are at it: Java 8 is quite old now. You might consider switching to a Java 11 baseline which would allow using the new [HttpClient](https://www.baeldung.com/java-9-http-client) instead of having to rely on the Apache HTTP Client and/or the plain URL class.

**Comment by amithkoujalgi** [comment]
Thanks for the info! So, this second GH action would be run upon merging a PR which would just run the tests ideally. Did I understand that right?

About Java 8, I thought of using the later versions but then I was wondering if there's someone who'd be relying on the older versions it might help them. What's your take on this?

**Comment by reckart** [comment]
On `pull_request` means that the build is running when the PR is opened or updated. That way you can check if contributions contain e.g. compile errors before merging them.

Wrt Java 8 - there may still be people using it, but in general there is now a move to a Java 17 baseline (at least in that part of the Java world where I live) - so I would consider a Java 11 baseline still quite conservative. For example the Spring framework is a pretty large player in the Java space and it requires Java 17 it its latest version (Spring 6).

Even if you don't move to Java 11, you might want to consider using Apache HTTP client consistently (i.e. replace usages of the plain URL/URLConnection with calls to HTTP client) - having that extra (powerful) dependency and then not using it consistently seems strange. At the point where you switch to e.g. Java 11 (LTS), that extra dependency could be dropped. Having fewer dependencies also has some benefits for a library.

**Comment by amithkoujalgi** [comment]
Yeah, that makes sense. I'll have a look at the GH actions for PRs.

About the Java version, I've updated all the Java 8 references to 11 now and I've updated the Apache HTTP client to `java.net.http.HttpClient`. I've removed the Apache HTTP client dependency as well. :)

Thanks for the pointers!

**Pull request merged**
